import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {GameEngine} from '../web/game/engine.js';
import {guideStep} from '../web/ui/guide.js';
const content=Object.fromEntries(await Promise.all(['items','recipes','locations','weather','enemies','events','scenarios','quests'].map(async n=>[n,JSON.parse(await readFile(`web/data/${n}.json`,'utf8'))])));
function prepared(){const g=new GameEngine(content,null,{seed:2026});for(const id of ['cooking_pot','canteen','fire_drill'])gear(g,id);Object.assign(g.state.stats,{stamina:100,calories:2800,hydration:2500});Object.assign(g.state.camp,{firepit:true,fire_cover:true,fire:500});g.state.nextWeather=1e8;g.state.items={wood:3,stone:3,fiber:4,scrap:2,dirty_water:2,raw_meat:1,fish:1,mushroom:2,water:1,herbs:4};return g;}
function gear(g,id,durability=content.items[id]?.durability){const x={id,uid:`${id}-${g.state.nextGear++}`,durability};g.state.gear.push(x);return x;}
test('every new scenario starts without free cookware, water carrier or fire drill',()=>{for(const scenario of Object.keys(content.scenarios)){const g=new GameEngine(content,null,{scenario});assert.deepEqual(g.state.gear.map(x=>x.id),['knife'],scenario);}});
test('boiling without a working pot is refused without consuming ingredients, time or RNG',()=>{for(const broken of [false,true]){const g=prepared();g.state.gear=g.state.gear.filter(x=>x.id!=='cooking_pot');if(broken)gear(g,'cooking_pot',0);const before=JSON.stringify(g.state);const result=g.perform('craft',{id:'water'});assert.equal(result.ok,false);assert.match(result.message,/pot/i);assert.equal(JSON.stringify(g.state),before);}});
test('the same carried pot boils repeated batches and only wears after cooking',()=>{const g=prepared();g.state.items.dirty_water=4;const pot=g.state.gear.find(x=>x.id==='cooking_pot');assert.ok(pot);const before=pot.durability;assert.equal(g.perform('craft',{id:'water'}).ok,true);assert.equal(g.perform('craft',{id:'water'}).ok,true);assert.equal(g.state.counters.waterBoiled,4);assert.equal(g.state.gear.filter(x=>x.id==='cooking_pot').length,1);assert.equal(pot.durability,before-4);});
test('food recipes distinguish the roasting spit from a cooking pot',()=>{const g=prepared();assert.match(g.reason('craft',{id:'cooked_meat'}),/spit/i);assert.match(g.reason('craft',{id:'cooked_fish'}),/spit/i);const spit=gear(g,'roasting_spit');const before=spit.durability;assert.equal(g.perform('craft',{id:'cooked_meat'}).ok,true);assert.equal(spit.durability,before-2);assert.equal(g.reason('craft',{id:'stew'}),null);g.state.gear=g.state.gear.filter(x=>x.id!=='cooking_pot');for(const id of ['stew','tea','medicine'])assert.match(g.reason('craft',{id}),/pot/i);});
test('rain interrupts cooking, refunds raw food and still wears the used utensil',()=>{const g=prepared();const pot=g.state.gear.find(x=>x.id==='cooking_pot');assert.ok(pot);g.state.camp.fire_cover=false;g.state.nextWeather=g.state.time+5;for(let seed=10000;seed<50000;seed++){const h=new GameEngine(content,g.state);h.state.seed=seed;const r=h.perform('craft',{id:'water'});if(r.ok&&h.state.weather==='rain'){assert.equal(h.state.items.dirty_water,2);assert.equal(h.state.counters.waterBoiled,0);assert.equal(h.state.gear.find(x=>x.id==='cooking_pot').durability,pot.durability-2);return;}}assert.fail('No rainy test seed');});
test('cold fire requires a fire drill; adding fuel to an existing flame does not',()=>{const g=prepared();g.state.gear=g.state.gear.filter(x=>x.id!=='fire_drill');g.state.camp.fire=0;assert.match(g.reason('fire'),/fire drill/i);g.state.camp.fire=90;assert.equal(g.reason('fire'),null);});
test('river water requires a carried vessel, worn by collecting water',()=>{const g=prepared();g.state.location='river';g.state.gear=g.state.gear.filter(x=>x.id!=='canteen');assert.match(g.reason('water'),/canteen/i);const canteen=gear(g,'canteen');const before=canteen.durability;g.state.items={};assert.equal(g.perform('water').ok,true);assert.equal(canteen.durability,before-1);});
test('mining uses a pickaxe and cave light, without wearing unrelated axes',()=>{const g=prepared();g.state.location='cave';const torch=gear(g,'torch'),axe=gear(g,'axe');g.state.equipment.tool=torch.uid;assert.match(g.reason('mine'),/pickaxe/i);const pick=gear(g,'pickaxe'),before={pick:pick.durability,torch:torch.durability,axe:axe.durability};assert.equal(g.perform('mine').ok,true);assert.equal(pick.durability,before.pick-4);assert.equal(torch.durability,before.torch-3);assert.equal(axe.durability,before.axe);});
test('kit gear cannot occupy equipment slots and each tool has an appropriate repair recipe',()=>{const g=prepared();for(const id of ['cooking_pot','canteen','fire_drill','roasting_spit','hammer','sewing_kit','pickaxe']){const item=content.items[id];assert.ok(item&&item.repair&&content.recipes[id],id);if(item.carried){const x=g.state.gear.find(x=>x.id===id)||gear(g,id);assert.match(g.reason('equip',{uid:x.uid}),/carried/i);}}});
test('tutorial recovers missing cookware through a real craft step',()=>{const g=prepared();g.state.gear=g.state.gear.filter(x=>x.id!=='cooking_pot');g.state.tutorial={step:6,active:true,version:2,usedFood:true,usedWater:false};g.state.items.water=0;const hint=guideStep(g,'craft',null);assert.equal(hint.recipe,'cooking_pot');assert.equal(g.reason('craft',{id:hint.recipe}),null);});
test('legacy saves preserve their earned inventory without injecting a starter tool set',()=>{const g=prepared(),old=structuredClone(g.state);delete old.toolsVersion;old.gear=old.gear.filter(x=>x.id==='knife');const upgraded=new GameEngine(content,old);assert.deepEqual(upgraded.state.gear,old.gear);assert.deepEqual(upgraded.state.stats,old.stats);assert.equal(upgraded.state.time,old.time);const reloaded=new GameEngine(content,upgraded.state);assert.deepEqual(reloaded.state.gear,upgraded.state.gear);});
