// Nature textures and physical foley only. No music, instrument samples, or oscillators.
let context,master,sfxBus,ambientBus,unlocked=false,paused=false,prefs={sound:true,ambient:true,sfxVolume:.65,ambientVolume:.32},scene=null;
const buffers=new Map(),loading=new Map(),layers=new Map(),voices=new Set(),timers=new Set();
const NAMES=['tap','pack','equip','swing','draw','chop','leaf','step1','step2','snowstep','hit','heavy','guard','mine','craft','book'];
function init(){if(context)return;context=new (window.AudioContext||window.webkitAudioContext)();master=context.createGain();sfxBus=context.createGain();ambientBus=context.createGain();master.gain.value=.7;sfxBus.connect(master);ambientBus.connect(master);const limiter=context.createDynamicsCompressor();limiter.threshold.value=-10;limiter.knee.value=8;limiter.ratio.value=8;limiter.attack.value=.003;limiter.release.value=.2;master.connect(limiter);limiter.connect(context.destination);}
async function load(name){if(buffers.has(name))return buffers.get(name);if(!loading.has(name))loading.set(name,(async()=>{const r=await fetch(`assets/audio/${name}.ogg`);if(!r.ok)throw new Error(name+' audio missing');const b=await context.decodeAudioData(await r.arrayBuffer());buffers.set(name,b);return b;})());return loading.get(name);}
export async function unlockAudio(settings){prefs={...prefs,...settings};unlocked=true;paused=false;try{init();await context.resume();applyVolumes();Promise.allSettled(NAMES.map(load));syncLayers();}catch{}}
export function configureAudio(settings){prefs={...prefs,...settings};if(context){applyVolumes();if(!prefs.sound){for(const v of voices){try{v.stop();}catch{}}voices.clear();for(const id of timers)clearTimeout(id);timers.clear();}syncLayers();}}
function applyVolumes(){const t=context.currentTime;sfxBus.gain.setTargetAtTime(prefs.sound?prefs.sfxVolume:0,t,.05);ambientBus.gain.setTargetAtTime(prefs.ambient?prefs.ambientVolume:0,t,.25);}
function later(fn,ms){const id=setTimeout(()=>{timers.delete(id);if(!paused)fn();},ms);timers.add(id);}
export async function sound(name='tap',enabled=true,volume=.55){if(!enabled||!prefs.sound||paused||!unlocked)return;try{init();if(context.state==='suspended')await context.resume();const b=await load(NAMES.includes(name)?name:'pack');if(!prefs.sound||paused)return;const source=context.createBufferSource(),gain=context.createGain();source.buffer=b;gain.gain.value=volume;source.connect(gain);gain.connect(sfxBus);voices.add(source);source.onended=()=>{voices.delete(source);source.disconnect();gain.disconnect();};source.start();}catch{}}
function noiseBuffer(type,seconds=18){const rate=context.sampleRate,n=Math.floor(rate*seconds),b=context.createBuffer(2,n,rate);let seed=7123+type.length*37;const rnd=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return (seed>>>0)/4294967296;};for(let ch=0;ch<2;ch++){const d=b.getChannelData(ch);let low=0,brown=0;const gusts=Array.from({length:20},()=>.35+rnd()*.65);for(let i=0;i<n;i++){const white=rnd()*2-1;low=low*.985+white*.015;brown=(brown+.013*white)/1.013;const pos=i/n*19,index=Math.floor(pos),frac=pos-index,gust=gusts[index]*(1-frac)+gusts[Math.min(19,index+1)]*frac;d[i]=type==='wind'?brown*gust*2.5:type==='river'?white*.08+low*.7:type==='rain'?white*.16+low*.2:type==='fire'?low*.18+white*.02:low*.3;}if(type==='fire'){for(let i=0;i<n;i++){if(rnd()>.99985){const size=Math.min(Math.floor(rate*.026),n-i);for(let j=0;j<size;j++)d[i+j]+=(rnd()*2-1)*Math.exp(-j/(rate*.004))*.3;}}}// Equal boundary values avoid a click at each loop seam.
 const fade=Math.min(512,n/10);for(let i=0;i<fade;i++){const f=i/fade;d[i]=d[i]*f+d[n-fade+i]*(1-f);}}
 return b;}
function makeLayer(name){const source=context.createBufferSource(),filter=context.createBiquadFilter(),gain=context.createGain();source.buffer=noiseBuffer(name);source.loop=true;filter.type=name==='wind'?'lowpass':'bandpass';filter.frequency.value=({wind:680,river:1300,rain:2600,fire:1800})[name];filter.Q.value=.35;gain.gain.value=0;source.connect(filter);filter.connect(gain);gain.connect(ambientBus);source.start();return {source,filter,gain};}
function syncLayers(){if(!context||!unlocked||paused)return;const s=scene;const targets={wind:0,river:0,rain:0,fire:0};if(prefs.ambient&&s){targets.wind=s.location==='cave'?.12:['mountain','summit'].includes(s.location)?.95:.34;targets.river=s.location==='river'?.8:0;targets.rain=['rain','storm'].includes(s.weather)?s.weather==='storm'?.8:.5:0;targets.fire=s.location==='camp'&&s.fire>0?.7:0;}for(const [name,value] of Object.entries(targets)){if(value&&!layers.has(name))layers.set(name,makeLayer(name));const layer=layers.get(name);if(layer)layer.gain.gain.setTargetAtTime(value,context.currentTime,.65);}}
export function updateAmbience(state,settings){prefs={...prefs,...settings};scene=state?{location:state.location,weather:state.weather,fire:state.camp.fire}:null;if(context){applyVolumes();syncLayers();}}
function texture(type){if(!prefs.sound||!unlocked||paused||!context)return;const source=context.createBufferSource(),filter=context.createBiquadFilter(),gain=context.createGain();source.buffer=noiseBuffer(type==='drink'?'river':type==='fire'?'fire':'rain',1);filter.type='lowpass';filter.frequency.value=type==='eat'?1500:type==='drink'?850:2100;source.connect(filter);filter.connect(gain);gain.connect(sfxBus);const t=context.currentTime;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.8,t+.09);gain.gain.exponentialRampToValueAtTime(.001,t+.65);voices.add(source);source.onended=()=>{voices.delete(source);source.disconnect();filter.disconnect();gain.disconnect();};source.start();source.stop(t+.7);}
export function actionSound(kind,options,result,before,content,settings){configureAudio(settings);if(!prefs.sound||paused)return;const battle=result.effects.battle;if(battle){if(battle.damageDealt){sound('swing',true,.5);later(()=>sound(options.move==='power'?'heavy':'hit',true,.65),170);}else if(options.move==='defend')sound('guard',true,.6);else sound('pack',true,.4);if(battle.damageTaken)later(()=>sound('hit',true,.45),battle.damageDealt?765:380);return;}
 if(kind==='gather'){sound('chop',true,.45);later(()=>sound('pack',true,.3),360);}else if(kind==='forage')sound('leaf',true,.6);else if(kind==='mine'){sound('mine',true,.55);later(()=>sound('mine',true,.35),310);}else if(kind==='craft'){sound('craft',true,.55);later(()=>sound('pack',true,.4),350);}else if(kind==='use'){sound(options.id==='bandage'?'leaf':'pack',true,.35);if(options.id!=='bandage'&&options.id!=='medicine')later(()=>texture(content.items[options.id]?.category==='water'||options.id==='tea'?'drink':'eat'),150);}else if(kind==='water'||kind==='fish')texture('drink');else if(['travel','explore','hunt'].includes(kind)){sound(before.weather==='snow'?'snowstep':'step1',true,.55);later(()=>sound('step2',true,.4),310);}else if(kind==='fire')texture('fire');else if(kind==='equip')sound('equip',true,.55);else sound('pack',true,.4);
}
export function suspendAudio(){paused=true;for(const id of timers)clearTimeout(id);timers.clear();for(const v of voices){try{v.stop();}catch{}}voices.clear();context?.suspend();}
export function resumeAudio(){if(!unlocked||document.hidden)return;paused=false;context?.resume();if(context){applyVolumes();syncLayers();}}
export function audioDiagnostics(){return {unlocked,paused,state:context?.state,activeLayers:[...layers].filter(([,v])=>v.gain.gain.value>0).map(([k])=>k),loaded:[...buffers.keys()],settings:{...prefs}};}
