import {icon,art,itemArt,esc,button,actionButton,duration,costMarkup} from './helpers.js';
import {equipped,weight,capacity} from '../game/inventory.js';
import {pageOf,pageSize,pager} from './layout.js';
const FILTERS={all:'All',resource:'Materials',food:'Provisions',gear:'Gear',medicine:'Remedies',quest:'Quest'};
export function packView(g,filter='all',page=0){
 const s=g.state,c=g.content,kg=weight(s,c),max=capacity(s);
 const entries=[...Object.entries(s.items).filter(([,n])=>n>0).map(([id,n])=>({id,n})),...s.gear.map(gear=>({...gear,n:1}))].filter(row=>filter==='all'||(filter==='food'?['food','water'].includes(c.items[row.id].category):c.items[row.id].category===filter));
 const p=pageOf(entries,page,pageSize('pack'));
 return `<div class="view-heading compact-heading"><div><span class="overline">TRAVEL PREPARED</span><h1>Your pack</h1></div><span class="weight-badge ${kg>max?'overweight':''}">${icon('backpack',24)}<b>${kg.toFixed(1)}</b> / ${max} kg</span></div>
 <div class="capacity-bar"><i style="width:${Math.min(100,kg/max*100)}%"></i></div>
 <div class="equipment-grid compact-equipment">${[['tool','Tool','axe'],['weapon','Weapon','sword'],['clothing','Clothing','coat-hanger']].map(([slot,label,ic])=>{const gear=equipped(s,c,slot);return button(`<span class="equipment-label">${label}</span>${gear?itemArt(gear,'equipment-art'):icon(ic,35,'empty-gear')}<b>${esc(gear?.name||'Equip')}</b><small>${gear?`${Math.round(gear.durability/c.items[gear.id].durability*100)}%`:''}</small>`,'equipment',{slot},`equipment-slot ${gear?'occupied':''}`);}).join('')}</div>
 <div class="collection-toolbar"><label><span class="sr-only">Inventory category</span><select data-filter="pack" aria-label="Inventory category">${Object.entries(FILTERS).map(([id,name])=>`<option value="${id}" ${filter===id?'selected':''}>${name}</option>`).join('')}</select></label><span>${entries.length} items</span></div>
 ${kg>max?'<p class="compact-notice text-danger">Overloaded · use or drop supplies.</p>':''}
 <div class="inventory-grid compact-inventory">${p.entries.length?p.entries.map(row=>{
  const item=c.items[row.id],active=row.uid&&s.equipment[item.slot]===row.uid,consumable=['food','water','medicine'].includes(item.category),useLabel=item.category==='water'?'Drink':item.category==='medicine'?'Use':'Eat';
  return `<article class="item-card ${active?'is-equipped':''}" data-item="${row.id}"><button class="item-info" data-ui="item-info" data-id="${row.id}" ${row.uid?`data-uid="${row.uid}"`:''}><span class="item-count">${active?icon('check',14):row.uid?'GEAR':'×'+row.n}</span><div class="item-art-stage">${itemArt(item,'inventory-art',false)}</div><b>${esc(item.name)}</b><small>${row.uid?`${row.durability}/${item.durability} durability`:`${(row.n*item.weight).toFixed(2)} kg`}</small>${row.uid?`<div class="meter"><i style="width:${row.durability/item.durability*100}%"></i></div>`:`<span class="item-nutrition">${item.calories?'+'+item.calories+' kcal ':''}${item.hydration?'+'+item.hydration+' ml':''}</span>`}</button><div class="item-card-footer">${item.risk?`<span class="raw-warning">${icon('warning',13)}Cook first</span>`:`<span>${item.carried?'CARRIED KIT':active?'EQUIPPED':''}</span>`}${consumable?actionButton(`${useLabel} ${icon('plus',14)}`,'use',{id:row.id},'item-quick',`aria-label="${useLabel} ${esc(item.name)}"`):row.uid&&!item.carried?actionButton(`${active?'Unequip':'Equip'} ${icon(active?'check':'arrow-up-right',14)}`,'equip',{uid:row.uid},`item-quick ${active?'active':''}`,`aria-label="${active?'Unequip':'Equip'} ${esc(item.name)}" ${row.durability<=0?'disabled':''}`):button(`Details ${icon('arrow-up-right',14)}`,'item-info',{id:row.id,...(row.uid?{uid:row.uid}:{})},'item-quick')}</div></article>`;
 }).join(''):`<div class="empty-state">${icon('backpack',48)}<h3>No supplies here yet.</h3></div>`}</div>${pager(p,'pack')}`;
}
const CATEGORIES={camp:'Camp',tools:'Tools',weapons:'Weapons',cooking:'Cooking',medicine:'Remedies',clothes:'Clothing',signal:'Radio'};
export function craftView(g,category='camp',page=0){
 const s=g.state,c=g.content,p=pageOf(Object.entries(c.recipes).filter(([,r])=>r.category===category),page,pageSize('craft'));
 return `<div class="view-heading compact-heading"><div><span class="overline">MAKE YOUR NEXT CHANCE</span><h1>${category==='camp'?'Build your refuge':'Workbench'}</h1></div><span class="tiny-badge">${s.counters.crafted} MADE</span></div>
 <div class="collection-toolbar"><label><span class="sr-only">Crafting category</span><select data-filter="craft" aria-label="Crafting category">${Object.entries(CATEGORIES).map(([id,name])=>`<option value="${id}" ${category===id?'selected':''}>${name}</option>`).join('')}</select></label><span>${p.total} recipes</span></div>
 ${s.location!=='camp'?`<div class="compact-notice">Craft at camp. ${button('Return','travel-dialog',{id:'camp'},'text-button')}</div>`:''}
 <div class="recipe-grid compact-recipes">${p.entries.map(([id,r])=>{
  const reason=g.reason('craft',{id}),done=r.structure&&Number(s.camp[r.structure])>=(r.level||1)||r.unique&&(s.items[r.item]||0)>0;
  const cost=Object.entries(r.cost).map(([item,n])=>`<span class="compact-ingredient ${(s.items[item]||0)>=n?'enough':'missing'}" title="${esc(c.items[item].name)}: ${n} needed, ${s.items[item]||0} owned">${itemArt(c.items[item])}<b>${n}</b></span>`).join('');
  return `<article class="recipe-card ${done?'built':''}" data-recipe="${id}"><button class="recipe-detail" data-ui="craft-dialog" data-id="${id}" aria-label="${esc(r.name)} details"><div class="recipe-visual">${art(r.art,'recipe-art','',false)}${done?`<span class="built-mark">${icon('check',15)}BUILT</span>`:''}</div><h3>${esc(r.name)}</h3></button><div class="recipe-cost">${cost}</div><div class="recipe-facts"><span>${icon('clock',15)}${duration(r.minutes)}</span><span>${icon('lightning',15)}${Math.ceil(g.effort('craft',{id}))}</span>${r.requiresFire?icon('flame',17):''}</div><div class="recipe-bottom"><small title="${esc(reason||'')}">${done?'Ready':reason||'Materials ready'}</small>${done?button('Built','craft-dialog',{id},'secondary-button',true):reason?button('Details','craft-dialog',{id},'secondary-button'):actionButton(r.structure?'Build':r.category==='cooking'?'Cook':'Craft','craft',{id},'primary-button')}</div></article>`;
 }).join('')}</div>${pager(p,'craft')}`;
}
