import { icon, art, itemArt, esc, button, duration, divider } from './helpers.js';
import { questProgress, activeMain, conditionProgress, revealedQuests } from '../game/quests.js';
import {pageOf,pager} from './layout.js';
function lockReason(l,g){if(l.requiresFlag)return `Find the ${g.content.items[l.requiresFlag]?.name.toLowerCase()||'previous clue'}.`;return Object.entries(l.requiresExplore||{}).map(([id,n])=>`Explore ${g.content.locations[id].name} ${n} time${n>1?'s':''}.`).join(' ');}
export function mapView(g,selected='forest'){
 const s=g.state,c=g.content,id=c.locations[selected]?selected:'forest',location=c.locations[id],unlocked=g.unlocked(id),current=s.location===id,route=g.routeTo(id),edges=new Set(),lines=[];
 for(const [from,l] of Object.entries(c.locations))for(const to of l.neighbors){const edge=[from,to].sort().join('-');if(edges.has(edge))continue;edges.add(edge);const end=c.locations[to],open=g.unlocked(from)&&g.unlocked(to);lines.push(`<line x1="${l.x}%" y1="${l.y}%" x2="${end.x}%" y2="${end.y}%" stroke="${open?'#c3a681':'#65636c'}" opacity="${open?'.65':'.25'}" stroke-width="1.5" stroke-dasharray="4 7"/>`);}
 return `<div class="view-heading compact-heading"><div><span class="overline">READ THE LAND</span><h1>The valley</h1></div><span class="tiny-badge">${s.discovered.length} / 8 OPEN</span></div><div class="map-frame">${art('assets/art/locations/mountain.webp','map-background')}<svg class="map-art" viewBox="0 0 800 470" preserveAspectRatio="none" aria-hidden="true"><defs><pattern id="map-grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" stroke="#aaa5a0" opacity=".08" fill="none"/></pattern></defs><rect width="800" height="470" fill="url(#map-grid)"/>${lines.join('')}</svg><div class="map-north">N<span>↑</span></div><span class="map-label map-mountains">ASHEN RIDGE</span><span class="map-label map-valley">THE QUIET VALLEY</span>${Object.entries(c.locations).map(([key,l])=>`<button class="map-node ${g.unlocked(key)?'open':'locked'} ${key===s.location?'current':''} ${key===id?'selected':''}" style="left:${l.x}%;top:${l.y}%" data-ui="select-location" data-id="${key}" aria-label="${esc(l.name)}${g.unlocked(key)?'':' locked'}"><span>${icon(g.unlocked(key)?l.icon:'lock',24)}</span><b>${esc(l.name)}</b>${key===s.location?'<small>YOU ARE HERE</small>':''}</button>`).join('')}<div class="map-legend"><span><i></i>Open trail</span><span><i class="muted"></i>Unknown</span></div></div><div class="map-location-panel"><div class="map-location-art">${art(location.art,'',location.name)}</div><div><span class="overline">${current?'YOU ARE HERE':unlocked?'TRAIL OPEN':'TRAIL LOCKED'}</span><h2>${esc(location.name)}</h2><p>${esc(unlocked?location.description:lockReason(location,g))}</p>${unlocked&&!current&&route?`<div class="travel-facts">${icon('clock',15)}${duration(route.minutes)} ${icon('lightning',15)}${Math.ceil(g.effort('travel',{id}))} stamina <span>·</span>${Math.round(g.danger(id)*100)}% wildlife pressure</div>`:''}</div>${current?button('View area','tab',{tab:'camp'},'secondary-button'):button(`Travel ${icon('arrow-right',18)}`,'travel-dialog',{id},'primary-button',!unlocked||!route)}</div>`;
}
const counters={woodGathered:'Firewood gathered',waterBoiled:'Water boiled',mealsCooked:'Meals cooked',fishCaught:'Trout caught',hunts:'Successful hunts',trapsHarvested:'Snares harvested',battlesWon:'Encounters won',oreMined:'Copper mined',locationsVisited:'Locations visited'};
export function conditionLabel(condition,c){return condition.flag?(condition.flag==='rescued'?'Rescue signal sent':c.items[condition.flag]?.name||condition.flag):condition.day?'Survival day':condition.item?c.items[condition.item].name:condition.structure?condition.structure==='firepit'?'Fire ring':`Shelter level`:counters[condition.counter]||'Fire lit';}
function questCard(s,c,q,main=false,index=0){
 const complete=s.quests.completed.includes(q.id),progress=questProgress(s,q),active=main&&activeMain(s,c)?.id===q.id;
 return `<article class="quest-card ${complete?'completed':''} ${active?'current':''}"><div class="quest-marker">${complete?icon('check',20):main?String(index+1).padStart(2,'0'):icon('flag',24)}</div><div class="quest-content"><div class="quest-title-row"><h3>${esc(q.title)}</h3><span class="quest-state">${complete?'COMPLETE':active?'ACTIVE':main?'LATER':''}</span></div>${complete?'':`<p>${esc(q.description)}</p><div class="quest-checklist">${q.conditions.map(condition=>{const p=conditionProgress(s,condition);return `<span class="${p.current>=p.target?'checked':''}">${icon(p.current>=p.target?'check':'circle',12)}${esc(conditionLabel(condition,c))}<b>${Math.min(p.current,p.target)} / ${p.target}</b></span>`;}).join('')}</div>`}<div class="quest-reward"><small>REWARD</small>${Object.entries(q.reward).map(([id,n])=>`<span title="${esc(c.items[id].name)}">${itemArt(c.items[id])}×${n} ${esc(c.items[id].name)}</span>`).join('')}</div></div></article>`;
}
export function journalView(g,group='main',page=null){
 const s=g.state,c=g.content,main=group==='main',list=revealedQuests(s,c,main?'main':'side'),active=main?activeMain(s,c):list.find(q=>!s.quests.completed.includes(q.id));
 const p=pageOf(list,page===null?Math.max(0,list.indexOf(active)):page,1);
 return `<div class="view-heading compact-heading"><div><span class="overline">A REASON TO SURVIVE</span><h1>The way home</h1></div><span class="tiny-badge">${s.quests.completed.length} COMPLETE</span></div><div class="quest-tabs">${button('Main journey','quest-group',{group:'main'},main?'selected':'')}${button('Side objectives','quest-group',{group:'side'},main?'':'selected')}</div>${list.length>1?`<div class="quest-chapters">${list.map((q,i)=>button(`${s.quests.completed.includes(q.id)?icon('check',15):String(i+1).padStart(2,'0')}`,'page',{scope:'quests',page:i},i===p.index?'selected':'')).join('')}</div>`:''}<div class="main-quests">${p.entries.map(q=>questCard(s,c,q,main,c.quests.main.indexOf(q))).join('')}${!list.length?'<div class="journal-unwritten">'+icon('notebook',38)+'<h3>Unwritten pages.</h3><p>New objectives appear as you explore and learn.</p></div>':''}</div><p class="journal-hint">${main?'The next chapter opens when this one ends.':'Discoveries reveal new objectives.'}</p><div class="journal-tools">${button(`${icon('notebook',20)}Field notes`,'history',{},'secondary-button')}${button(`${icon('share-network',18)}Share`,'share',{},'text-button')}</div>`;
}
