import { art, itemArt, icon, esc, duration } from './helpers.js';
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const moves={gather:['Gathering','axe'],forage:['Foraging','herbs'],mine:['Mining','axe'],fish:['Fishing','fish'],water:['Collecting water','dirty_water'],hunt:['Hunting','bow'],setTrap:['Setting a snare','trap'],checkTrap:['Checking the snare','trap'],rest:['Resting',null],sleep:['Sleeping',null],fire:['Tending the fire',null],signal:['Transmitting','radio'],explore:['Exploring',null],travel:['Travelling',null],equip:['Equipping',null],repair:['Repairing',null],drop:['Packing',null],resolveEvent:['On the trail',null]};
let last=null;
const animate=(el,frames,options)=>{if(!el)return Promise.resolve();const a=el.animate(frames,{fill:'none',easing:'cubic-bezier(.2,.8,.2,1)',...options});return a.finished.catch(()=>{});};
function hitNumber(target,n,kind){if(!target||!n)return;const el=document.createElement('span');el.className=`hit-number ${kind}`;el.textContent=`−${Number(n.toFixed(1))}`;target.append(el);animate(el,[{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)',offset:.18},{opacity:0,transform:'translateY(-42px)'}],{duration:730}).then(()=>el.remove());}
function slash(target,power){if(!target)return;const el=document.createElement('i');el.className='battle-slash';target.append(el);animate(el,[{opacity:0,transform:'translate(-28px,25px) rotate(-30deg) scaleX(.1)'},{opacity:power?.9:.65,transform:'translate(0,0) rotate(-30deg) scaleX(1)',offset:.4},{opacity:0,transform:'translate(18px,-14px) rotate(-30deg) scaleX(.85)'}],{duration:270}).then(()=>el.remove());}
async function battleFX(options,result,before){const b=result.effects.battle,stage=document.querySelector('.battle-stage'),enemy=stage?.querySelector('.battle-enemy'),hero=stage?.querySelector('.battle-survivor');if(!stage)return;
 if(b.damageDealt){animate(hero,[{transform:'translateX(0)'},{transform:'translateX(16px) rotate(2deg)',offset:.5},{transform:'translateX(0)'}],{duration:320});await wait(155);slash(enemy,options.move==='power');hitNumber(enemy,b.damageDealt,'dealt');animate(enemy,[{transform:'translateX(0)',filter:'brightness(1)'},{transform:'translateX(13px) rotate(3deg)',filter:'brightness(1.45)',offset:.24},{transform:'translateX(0)',filter:'brightness(1)'}],{duration:380});const hp=stage.querySelector('.battle-enemy-meter i');if(hp){const start=Number(stage.dataset.enemyHp),max=Number(stage.dataset.enemyMax);hp.style.width=Math.max(0,start-b.damageDealt)/max*100+'%';const label=enemy.querySelector(':scope > span');if(label)label.textContent=Math.max(0,start-b.damageDealt)+' / '+max+' HP';}await wait(350);}
 else if(options.move==='defend'){const guard=document.createElement('div');guard.className='guard-aura';guard.innerHTML=icon('shield',68);hero?.append(guard);animate(guard,[{opacity:0,transform:'scale(.85)'},{opacity:.85,transform:'scale(1)',offset:.35},{opacity:0,transform:'scale(1.08)'}],{duration:650}).then(()=>guard.remove());}
 else if(options.move==='flee')animate(hero,[{opacity:1,transform:'translateX(0)'},{opacity:b.fled?0:.65,transform:'translateX(-24px)'}],{duration:520});
 if(b.damageTaken){await wait(b.damageDealt?110:230);animate(enemy,[{transform:'translateX(0)'},{transform:'translateX(-20px) rotate(-2deg)',offset:.5},{transform:'translateX(0)'}],{duration:300});await wait(150);hitNumber(hero,b.damageTaken,'received');animate(hero,[{transform:'translateX(0)',filter:'brightness(1)'},{transform:'translateX(-9px)',filter:'brightness(1.25)',offset:.3},{transform:'translateX(0)',filter:'brightness(1)'}],{duration:300});await wait(260);}
 const healthLabel=hero?.querySelector(':scope > span');if(healthLabel)healthLabel.textContent=`YOU · ${Math.round(before.stats.health+result.effects.stats.health)} HP`;
 if(b.victory)await animate(enemy,[{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(15px) scale(.98)'}],{duration:340});else await wait(160);
}
export async function animateAction(kind,options,result,before,content,settings){last={kind,options:{...options},effects:structuredClone(result.effects)};if(!settings.motion||matchMedia('(prefers-reduced-motion: reduce)').matches||document.hidden)return;
 if(result.effects.battle&&document.querySelector('.battle-stage')){await battleFX(options,result,before);return;}
 if(['equip','drop'].includes(kind)){await animate(document.querySelector(`[data-item="${options.id||before.gear.find(g=>g.uid===options.uid)?.id}"]`),[{transform:'scale(1)'},{transform:'scale(.975)',offset:.4},{transform:'scale(1)'}],{duration:230});return;}
 const recipe=kind==='craft'?content.recipes[options.id]:null,used=kind==='use'?content.items[options.id]:null;
 const [label,itemId]=moves[kind]||[kind==='craft'?'Crafting':used?.category==='water'||options.id==='tea'?'Drinking':used?.category==='medicine'?'Treating':'Eating',null];
 const tool=before.gear.find(g=>g.uid===before.equipment.tool&&g.durability>0),weapon=before.gear.find(g=>g.uid===before.equipment.weapon&&g.durability>0),axe=before.gear.find(g=>['axe','iron_axe'].includes(g.id)&&g.durability>0);
 const matching=kind==='gather'?tool?.id||'wood':kind==='mine'?axe?.id:kind==='hunt'?weapon?.id:kind==='fish'?'fishing_rod':itemId;
 const source=recipe?.art||used?.art||content.items[matching]?.art;
 const direction=kind==='use'?(used.category==='water'||options.id==='tea'?'drink':used.category==='medicine'?'treat':'eat'):kind;
 const root=document.createElement('div');root.className=`action-theatre fx-${direction}`;root.setAttribute('aria-hidden','true');root.dataset.kind=kind;
 const gained=Object.entries(result.effects.gained);
 const changes=['calories','hydration','health','stamina'].filter(k=>Math.abs(result.effects.stats[k])>=1).map(k=>`<span class="${result.effects.stats[k]>0?'gain':'loss'}">${icon(({calories:'bowl-food',hydration:'drop',health:'heart',stamina:'lightning'})[k],17)}${result.effects.stats[k]>0?'+':''}${Math.round(result.effects.stats[k])}${({calories:' kcal',hydration:' ml',health:' HP',stamina:''})[k]}</span>`).join('');
 root.innerHTML=`<div class="action-cinema"><div class="cinema-landscape">${art(content.locations[kind==='travel'?options.id:before.location].art,'','',false)}</div><div class="cinema-shade"></div><span class="cinema-label">${esc(label)}</span><div class="cinema-object">${source?art(source,'fx-object','',false):icon(['sleep','rest'].includes(kind)?'moon':kind==='fire'?'flame':'compass',105)}<div class="fx-ripple"></div>${['gather','craft','mine','fire'].includes(kind)?'<div class="fx-sparks"><i></i><i></i><i></i><i></i><i></i></div>':''}${direction==='drink'?'<div class="fx-droplets"><i></i><i></i><i></i></div>':''}</div><div class="cinema-loot">${gained.slice(0,4).map(([id,n],i)=>`<span style="--delay:${i*65}ms">${itemArt(content.items[id],'',false)}<b>+${n}</b></span>`).join('')}</div><div class="cinema-result">${changes}<small>${duration(result.effects.minutes)}</small></div></div>`;
 document.body.append(root);await animate(root,[{opacity:0},{opacity:1}],{duration:150});await wait(kind==='craft'||kind==='sleep'?790:kind==='use'?630:670);await animate(root,[{opacity:1},{opacity:0,transform:'translateY(5px)'}],{duration:170});root.remove();
}
export function animateHud(before,after,enabled){if(!enabled||matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(const key of ['health','stamina','calories','hydration']){const el=document.querySelector(`[data-stat="${key}"]`);if(!el)continue;const diff=after.stats[key]-before.stats[key];if(Math.abs(diff)<.7)continue;animate(el,[{backgroundColor:'transparent'},{backgroundColor:diff>0?'rgba(211,167,122,.13)':'rgba(196,139,124,.06)',offset:.25},{backgroundColor:'transparent'}],{duration:620});const value=el.querySelector('.stat-number'),small=value.querySelector('small')?.outerHTML||'',start=before.stats[key],end=after.stats[key],began=performance.now();const frame=now=>{if(!value.isConnected)return;const t=Math.min(1,(now-began)/400),n=Math.round(start+(end-start)*(1-Math.pow(1-t,3)));value.innerHTML=n.toLocaleString('en-US')+small;if(t<1)requestAnimationFrame(frame);};requestAnimationFrame(frame);}}
export function motionDiagnostics(){return last;}
