import {art,esc,button,icon} from './helpers.js';
export function storyView(content,state,replay=false,index=0,narration=true){
  const step=replay?index:state.prologue.step,scene=content.story[step],last=step===content.story.length-1;
  return `<main class="story-screen" aria-label="Your story"><div class="story-frame">${art(scene.art,'story-background story-'+scene.id,'Ashen Valley: '+scene.id,false)}<div class="story-shade"></div><header><span>WILDFALL <small>LAST EMBER</small></span><div class="story-tools"><button class="story-audio" data-ui="story-voice" aria-label="${narration?'Mute narration':'Enable narration'}" aria-pressed="${narration}" title="${narration?'Narration on':'Narration off'}">${icon(narration?'speaker-high':'speaker-slash',20)}</button><button class="story-audio" data-ui="story-replay-voice" aria-label="Replay narration" title="Replay narration" ${narration?'':'disabled'}>${icon('arrow-counter-clockwise',20)}</button>${button(replay?'Close':'Skip story',replay?'story-close':'story-skip',{},'story-skip')}</div></header><section class="story-copy" aria-live="polite"><div class="story-caption"><span class="overline">PROLOGUE · ${String(step+1).padStart(2,'0')} / 05</span><span class="story-voice-status">${narration?'VOICE ON':'VOICE OFF'}</span></div><h1>${esc(scene.title)}</h1><p>${esc(scene.variants?.[state.scenario]||scene.text)}</p><div class="story-progress">${content.story.map((s,i)=>`<i class="${i<=step?'read':''}"></i>`).join('')}</div><div class="story-controls">${step?'<button class="secondary-button story-back" data-ui="story-back" aria-label="Previous scene">'+icon('arrow-left',20)+'</button>':''}${button(`${last?(replay?'Return':'Make camp'):'Continue'} ${icon('arrow-right',19)}`,last?(replay?'story-close':'story-skip'):'story-next',{},'primary-button')}</div></section></div></main>`;
}
export function updateStoryVoice(root,enabled){
 const toggle=root.querySelector('[data-ui="story-voice"]');if(!toggle)return;
 toggle.innerHTML=icon(enabled?'speaker-high':'speaker-slash',20);toggle.setAttribute('aria-pressed',String(enabled));toggle.setAttribute('aria-label',enabled?'Mute narration':'Enable narration');toggle.title=enabled?'Narration on':'Narration off';
 root.querySelector('[data-ui="story-replay-voice"]').disabled=!enabled;
}
export function updateStoryNarration(root,playing,enabled){const status=root.querySelector('.story-voice-status');if(status){status.textContent=playing?'NARRATING':enabled?'VOICE ON':'VOICE OFF';status.classList.toggle('playing',playing);}}
